import * as Clipboard from "expo-clipboard";
import * as Linking from "expo-linking";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import * as WebBrowser from "expo-web-browser";
import React from "react";
import {
  KeyboardAvoidingView,
  Platform,
  Pressable,
  Text,
  TextInput,
  View,
} from "react-native";
import Svg, { Path } from "react-native-svg";

import { supabase } from "@/lib/supabase";

type RateLimitResult = {
  allowed: boolean;
  retry_after_seconds: number;
  attempts_left: number;
};

const MAX_ATTEMPTS_PER_WINDOW = 5;
const OAUTH_PROVIDER = "google";
const OAUTH_REDIRECT_PATH = "auth/callback";
const NATIVE_OAUTH_REDIRECT_URL = "batbnb://auth/callback";

function GoogleBrandIcon({ size = 18 }: { size?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 48 48" fill="none">
      <Path
        fill="#FFC107"
        d="M43.611 20.083H42V20H24v8h11.303C33.654 32.657 29.198 36 24 36c-6.627 0-12-5.373-12-12s5.373-12 12-12c3.059 0 5.842 1.154 7.953 3.047l5.657-5.657C34.046 6.053 29.268 4 24 4 12.955 4 4 12.955 4 24s8.955 20 20 20 20-8.955 20-20c0-1.341-.138-2.65-.389-3.917z"
      />
      <Path
        fill="#FF3D00"
        d="M6.306 14.691l6.571 4.819C14.655 16.108 18.961 12 24 12c3.059 0 5.842 1.154 7.953 3.047l5.657-5.657C34.046 6.053 29.268 4 24 4c-7.681 0-14.41 4.337-17.704 10.691z"
      />
      <Path
        fill="#4CAF50"
        d="M24 44c5.166 0 9.86-1.977 13.409-5.192l-6.19-5.238C29.172 35.091 26.715 36 24 36c-5.177 0-9.625-3.299-11.289-7.874l-6.52 5.025C9.446 39.556 16.227 44 24 44z"
      />
      <Path
        fill="#1976D2"
        d="M43.611 20.083H42V20H24v8h11.303c-.793 2.237-2.231 4.166-4.087 5.571l6.19 5.238C36.971 39.205 44 34 44 24c0-1.341-.138-2.65-.389-3.917z"
      />
    </Svg>
  );
}

function resolveOAuthRedirectUrl() {
  // Use a stable custom scheme in native builds so Supabase can safely allow-list it.
  // In Expo Go, fall back to the runtime URL generated by Expo.
  const expoGoUrl = Linking.createURL(OAUTH_REDIRECT_PATH);
  const isExpoGo =
    expoGoUrl.startsWith("exp://") || expoGoUrl.startsWith("exps://");
  if (isExpoGo) {
    return expoGoUrl;
  }
  return NATIVE_OAUTH_REDIRECT_URL;
}

export default function LoginScreen() {
  const router = useRouter();
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const params = useLocalSearchParams<{ mode?: string }>();
  const initialSignUp = params?.mode === "signup";
  const [isSignUpMode, setIsSignUpMode] = React.useState<boolean>(
    Boolean(initialSignUp),
  );
  const [isSubmitting, setIsSubmitting] = React.useState(false);
  const [isOAuthSubmitting, setOAuthSubmitting] = React.useState(false);
  const [oauthDebugNotice, setOAuthDebugNotice] = React.useState<string | null>(
    null,
  );
  const [errorMessage, setErrorMessage] = React.useState<string | null>(null);
  const [successMessage, setSuccessMessage] = React.useState<string | null>(
    null,
  );
  const clearDebugNoticeTimeoutRef = React.useRef<ReturnType<
    typeof setTimeout
  > | null>(null);

  const normalizedEmail = email.trim().toLowerCase();
  const isBusy = isSubmitting || isOAuthSubmitting;
  const oauthRedirectUrl = React.useMemo(() => resolveOAuthRedirectUrl(), []);

  React.useEffect(() => {
    return () => {
      if (clearDebugNoticeTimeoutRef.current) {
        clearTimeout(clearDebugNoticeTimeoutRef.current);
      }
    };
  }, []);

  const checkRateLimit = React.useCallback(async (targetEmail: string) => {
    const { data, error } = await supabase.rpc("check_login_rate_limit", {
      p_email: targetEmail,
    });

    if (error) {
      return { status: null as RateLimitResult | null, error: error.message };
    }

    const firstEntry = Array.isArray(data) ? data[0] : null;
    if (!firstEntry) {
      return { status: null as RateLimitResult | null, error: null };
    }

    return {
      status: {
        allowed: Boolean(firstEntry.allowed),
        retry_after_seconds: Number(firstEntry.retry_after_seconds ?? 0),
        attempts_left: Number(
          firstEntry.attempts_left ?? MAX_ATTEMPTS_PER_WINDOW,
        ),
      },
      error: null,
    };
  }, []);

  const recordAttempt = React.useCallback(
    async (targetEmail: string, success: boolean) => {
      const { error } = await supabase.rpc("record_login_attempt", {
        p_email: targetEmail,
        p_success: success,
      });

      return error?.message ?? null;
    },
    [],
  );

  const handleSubmit = React.useCallback(async () => {
    setErrorMessage(null);
    setSuccessMessage(null);

    if (!normalizedEmail.includes("@")) {
      setErrorMessage("Enter a valid email address.");
      return;
    }

    if (password.length < 6) {
      setErrorMessage("Password must be at least 6 characters.");
      return;
    }

    setIsSubmitting(true);

    if (isSignUpMode) {
      const { data, error } = await supabase.auth.signUp({
        email: normalizedEmail,
        password,
      });

      if (error) {
        setErrorMessage(error.message);
        setIsSubmitting(false);
        return;
      }

      if (data.session) {
        setSuccessMessage("Account created. You are now signed in.");
        router.replace("/");
      } else {
        setSuccessMessage(
          "Account created. Check your email for the confirmation link.",
        );
      }

      setIsSubmitting(false);
      return;
    }

    const initialRateLimit = await checkRateLimit(normalizedEmail);
    if (initialRateLimit.status && !initialRateLimit.status.allowed) {
      const seconds = Math.max(1, initialRateLimit.status.retry_after_seconds);
      setErrorMessage(
        `Too many login attempts. Try again in ${seconds} second${seconds === 1 ? "" : "s"}.`,
      );
      setIsSubmitting(false);
      return;
    }

    const signInResult = await supabase.auth.signInWithPassword({
      email: normalizedEmail,
      password,
    });

    await recordAttempt(normalizedEmail, !signInResult.error);

    if (signInResult.error) {
      const postFailureRateLimit = await checkRateLimit(normalizedEmail);
      if (postFailureRateLimit.status && !postFailureRateLimit.status.allowed) {
        const seconds = Math.max(
          1,
          postFailureRateLimit.status.retry_after_seconds,
        );
        setErrorMessage(
          `Too many login attempts. Try again in ${seconds} second${seconds === 1 ? "" : "s"}.`,
        );
      } else if (postFailureRateLimit.status) {
        setErrorMessage(
          `Invalid email or password. ${postFailureRateLimit.status.attempts_left} attempt${postFailureRateLimit.status.attempts_left === 1 ? "" : "s"} left in this 1-minute window.`,
        );
      } else {
        setErrorMessage(signInResult.error.message);
      }
      setIsSubmitting(false);
      return;
    }

    setSuccessMessage("Signed in successfully.");
    setIsSubmitting(false);
    router.replace("/");
  }, [
    checkRateLimit,
    isSignUpMode,
    normalizedEmail,
    password,
    recordAttempt,
    router,
  ]);

  const handleOAuthSignIn = React.useCallback(async () => {
    setErrorMessage(null);
    setSuccessMessage(null);
    setOAuthSubmitting(true);

    const redirectTo = oauthRedirectUrl;
    console.log("👉 COPY THIS TO SUPABASE REDIRECT URLs:", redirectTo);

    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: OAUTH_PROVIDER,
      options: {
        redirectTo,
        skipBrowserRedirect: true,
      },
    });

    if (error) {
      setErrorMessage(error.message);
      setOAuthSubmitting(false);
      return;
    }

    if (!data?.url) {
      setErrorMessage(
        "OAuth login did not return an auth URL. Check your Supabase provider setup.",
      );
      setOAuthSubmitting(false);
      return;
    }

    const authResult = await WebBrowser.openAuthSessionAsync(
      data.url,
      redirectTo,
    );

    console.log("🔍 Browser Session Result:", JSON.stringify(authResult, null, 2));

    if (authResult.type === "success" && authResult.url) {
      console.log("✅ Browser returned success URL, processing session...");

      // Helper to parse tokens from the URL hash/query
      const parseParam = (url: string, key: string) => {
        const parts = url.split(/[#?&]/);
        for (const part of parts) {
          if (part.startsWith(`${key}=`)) return part.split("=")[1];
        }
        return null;
      };

      const accessToken = parseParam(authResult.url, "access_token");
      const refreshToken = parseParam(authResult.url, "refresh_token");

      if (accessToken && refreshToken) {
        const { error: sessionError } = await supabase.auth.setSession({
          access_token: accessToken,
          refresh_token: refreshToken,
        });

        if (sessionError) {
          setErrorMessage(`Session error: ${sessionError.message}`);
          setOAuthSubmitting(false);
          return;
        }

        console.log("🎉 OAuth session set successfully!");
        router.replace("/");
        return;
      }

      // If no tokens found, fallback to navigating to callback screen
      router.replace(authResult.url as any);
      return;
    }

    if (authResult.type !== "success") {
      if (authResult.type === "cancel" || authResult.type === "dismiss") {
        setErrorMessage("OAuth sign-in was cancelled.");
      } else {
        setErrorMessage("OAuth sign-in could not be completed.");
      }
      setOAuthSubmitting(false);
      return;
    }

    // On success, Expo Router will intercept the deep link and navigate to our OAuth callback screen.
    // The callback screen will handle the session exchange and redirect.
  }, [oauthRedirectUrl]);

  const handleCopyOAuthRedirectUrl = React.useCallback(async () => {
    const didCopy = await Clipboard.setStringAsync(oauthRedirectUrl);
    if (!didCopy) {
      setOAuthDebugNotice("Could not copy. Please copy manually.");
      return;
    }

    setOAuthDebugNotice("Redirect URL copied.");

    if (clearDebugNoticeTimeoutRef.current) {
      clearTimeout(clearDebugNoticeTimeoutRef.current);
    }

    clearDebugNoticeTimeoutRef.current = setTimeout(() => {
      setOAuthDebugNotice(null);
      clearDebugNoticeTimeoutRef.current = null;
    }, 1800);
  }, [oauthRedirectUrl]);

  return (
    <KeyboardAvoidingView
      style={{ flex: 1, backgroundColor: "#09090b" }}
      behavior={Platform.OS === "ios" ? "padding" : "height"}
    >
      <Stack.Screen options={{ headerShown: false }} />

      <View className="flex-1 justify-center px-6">
        <View className="border border-zinc-800 bg-zinc-950 rounded-3xl p-6">
          <Text className="text-zinc-100 text-3xl font-bold tracking-tight">
            {isSignUpMode ? "Create account" : "Welcome back"}
          </Text>
          <Text className="text-zinc-400 mt-2 text-sm">
            {isSignUpMode
              ? "Create an account with Google OAuth or email/password."
              : "Sign in to continue to BatBnB."}
          </Text>

          <Pressable
            onPress={handleOAuthSignIn}
            disabled={isBusy}
            className={`mt-6 rounded-xl py-3.5 items-center border ${
              isBusy
                ? "bg-zinc-900 border-zinc-700"
                : "bg-zinc-900 border-zinc-600"
            }`}
          >
            <View className="flex-row items-center">
              <GoogleBrandIcon size={18} />
              <Text className="text-zinc-100 font-semibold ml-2">
                {isOAuthSubmitting
                  ? "Connecting Google..."
                  : "Continue with Google"}
              </Text>
            </View>
          </Pressable>

          <View className="mt-4 flex-row items-center">
            <View className="flex-1 h-px bg-zinc-800" />
            <Text className="text-zinc-500 text-xs mx-3">or</Text>
            <View className="flex-1 h-px bg-zinc-800" />
          </View>

          <View className="mt-6">
            <Text className="text-zinc-300 text-xs mb-2">Email</Text>
            <TextInput
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              keyboardType="email-address"
              placeholder="you@example.com"
              placeholderTextColor="#71717a"
              className="bg-zinc-900 border border-zinc-800 rounded-xl px-4 py-3 text-zinc-100"
            />
          </View>

          <View className="mt-4">
            <Text className="text-zinc-300 text-xs mb-2">Password</Text>
            <TextInput
              value={password}
              onChangeText={setPassword}
              secureTextEntry
              placeholder="At least 6 characters"
              placeholderTextColor="#71717a"
              className="bg-zinc-900 border border-zinc-800 rounded-xl px-4 py-3 text-zinc-100"
            />
          </View>

          {errorMessage ? (
            <Text className="text-red-300 text-xs mt-4">{errorMessage}</Text>
          ) : null}

          {successMessage ? (
            <Text className="text-emerald-300 text-xs mt-4">
              {successMessage}
            </Text>
          ) : null}

          <Pressable
            onPress={handleSubmit}
            disabled={isBusy}
            className={`mt-6 rounded-xl py-3.5 items-center ${
              isBusy ? "bg-indigo-500/70" : "bg-indigo-600"
            }`}
          >
            <Text className="text-white font-semibold">
              {isSubmitting
                ? "Please wait..."
                : isSignUpMode
                  ? "Create account"
                  : "Sign in"}
            </Text>
          </Pressable>

          <Pressable
            onPress={() => {
              setIsSignUpMode((current) => !current);
              setErrorMessage(null);
              setSuccessMessage(null);
            }}
            className="mt-4 items-center"
          >
            <Text className="text-indigo-300 text-sm">
              {isSignUpMode
                ? "Already have an account? Sign in"
                : "Need an account? Create one"}
            </Text>
          </Pressable>
        </View>
      </View>
    </KeyboardAvoidingView>
  );
}
